---
functional:
  - Пользователь должен иметь возможность устанавливать сложность игр
  - Пользователь должен иметь возможность создавать игры с другим пользователем, с друзьями и с ботом
  - Пользователь должен иметь возможность выбирать время на решения задач
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6
