---
functional:
  - Пользователь должен иметь возможность устанавливать сложность игр
  - Пользователь должен иметь возможность создавать игры с другим пользователем, с друзьями и с ботом
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность выбирать время на решения задач
  - Пользователь должен иметь возможность просматривать историю других игр
  - Пользователь должен иметь возможность видеть таблицу лидеров среди игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Opera, Firefox, Chrome, Яндекс Браузер
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен соответствовать законодательным актам РФ
  
